// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkeWUAW03IKO_fNCjSoUlWgT7kn6ZVvs4',
    appId: '1:821218402375:web:56129169f4a3e35199d162',
    messagingSenderId: '821218402375',
    projectId: 'spotify-clone-42cc3',
    authDomain: 'spotify-clone-42cc3.firebaseapp.com',
    storageBucket: 'spotify-clone-42cc3.firebasestorage.app',
    measurementId: 'G-MKZ3T49GTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMqvvHY8Dvc3dO18CTE87YiTkmnM_vazs',
    appId: '1:821218402375:android:28d6a590313b2f1799d162',
    messagingSenderId: '821218402375',
    projectId: 'spotify-clone-42cc3',
    storageBucket: 'spotify-clone-42cc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDluoqyszsAkVRauIiYlPI6ZuwbJdSxzdo',
    appId: '1:821218402375:ios:d728884103663c4699d162',
    messagingSenderId: '821218402375',
    projectId: 'spotify-clone-42cc3',
    storageBucket: 'spotify-clone-42cc3.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDluoqyszsAkVRauIiYlPI6ZuwbJdSxzdo',
    appId: '1:821218402375:ios:d728884103663c4699d162',
    messagingSenderId: '821218402375',
    projectId: 'spotify-clone-42cc3',
    storageBucket: 'spotify-clone-42cc3.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkeWUAW03IKO_fNCjSoUlWgT7kn6ZVvs4',
    appId: '1:821218402375:web:03eafee74194e2db99d162',
    messagingSenderId: '821218402375',
    projectId: 'spotify-clone-42cc3',
    authDomain: 'spotify-clone-42cc3.firebaseapp.com',
    storageBucket: 'spotify-clone-42cc3.firebasestorage.app',
    measurementId: 'G-DW79RYG97X',
  );
}
